// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGkVssLib5iOoR6DB5obBFySe77JFSYZw',
    appId: '1:1032898984443:web:db7903e0befa350e3eb35e',
    messagingSenderId: '1032898984443',
    projectId: 'base-1cf20',
    authDomain: 'base-1cf20.firebaseapp.com',
    storageBucket: 'base-1cf20.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmZcGWa0ZnrsY_LX9mTyk53hXk_mjx8DM',
    appId: '1:1032898984443:android:adf56d7d894464f53eb35e',
    messagingSenderId: '1032898984443',
    projectId: 'base-1cf20',
    storageBucket: 'base-1cf20.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6jes6Ddsjzftc8-8jV35kPvgrByBSaRY',
    appId: '1:1032898984443:ios:26c12d22f788ec283eb35e',
    messagingSenderId: '1032898984443',
    projectId: 'base-1cf20',
    storageBucket: 'base-1cf20.firebasestorage.app',
    iosBundleId: 'com.example.todoAppFirebase',
  );
}
